builds:
  - main: main.go
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
    env:
      - GO111MODULE=on
archive:
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
