builds:
  - ldflags:
    - -s -w -X "main.goversion={{.Env.GOVERSION}}"
  - main: main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  name_template: '{{.ProjectName}}-{{.Env.GOVERSION_NR}}'
  files:
    - none*
